### ISSUE TITLE
ext-grpc を CI 上でも使えるようにする

### ISSUE THREAD

**Issue by sayuprc** [sayuprc/isekai-journey-admin-panel#77]
```yaml
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: grpc
          tools: composer
```
